# Generated by Django 6.0.2 on 2026-02-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['external_id'], name='employees_e_externa_c904bb_idx'), models.Index(fields=['department', 'is_active'], name='employees_e_departm_c5cc9c_idx')],
            },
        ),
    ]
