# Generated by Django 6.0.2 on 2026-02-23 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('first_entry', models.DateTimeField(blank=True, null=True)),
                ('last_exit', models.DateTimeField(blank=True, null=True)),
                ('worked_hours', models.FloatField()),
                ('lateness_minutes', models.PositiveIntegerField()),
                ('overtime_minutes', models.PositiveIntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='employees.employee')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='unique_employee_date_daily_summary')],
            },
        ),
    ]
