# Generated by Django 5.2.11 on 2026-03-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_device_mac_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='address',
            field=models.CharField(blank=True, help_text='Реальный IP устройства. По нему устройство сопоставляется с запросом при приходе событий.', max_length=255, verbose_name='Адрес (IP или URL)'),
        ),
    ]
